const commodityMap: { [key: string]: string } = {
  'Tomato Small(Local)': 'गोलभेडा सानो(लोकल)',
  'Tomato Small(Tunnel)': 'गोलभेडा सानो(टनेल)',
  'Tomato Small(Indian)': 'गोलभेडा सानो(भारतीय)',
  'Potato Red': 'आलु रातो',
  'Potato Red(Indian)': 'आलु रातो(भारतीय)',
  'Potato Red(Mude)': 'आलु रातो(मुडे)',
  'Potato White': 'आलु सेतो',
  'Onion Dry (Indian)': 'प्याज सुकेको (भारतीय)',
  'Carrot(Local)': 'गाजर(लोकल)',
  'Cabbage(Local)': 'बन्दा(लोकल)',
  'Cabbage(Terai)': 'बन्दा(तराई)',
  'Cauli Local': 'काउली स्थानिय',
  'Cauli Local(Jyapu)': 'स्थानीय काउली(ज्यापु)',
  'Raddish White(Local)': 'मूला सेतो(लोकल)',
  'Raddish White(Hybrid)': 'सेतो मूला(हाइब्रीड)',
  'Brinjal Long': 'भन्टा लाम्चो',
  'Brinjal Round': 'भन्टा डल्लो',
  'Cow pea(Long)': 'बोडी(तने)',
  'Cowpea(Short)': 'मकै बोडी',
  'French Bean(Local)': 'घिउ सिमी(लोकल)',
  'French Bean(Hybrid)': 'घिउ सिमी(हाइब्रीड)',
  'French Bean(Rajma)': 'घिउ सिमी(राजमा)',
  'Soyabean Green': 'भटमासकोशा',
  'Bitter Gourd': 'तितो करेला',
  'Bottle Gourd': 'लौका',
  'Pointed Gourd(Local)': 'परवर(लोकल)',
  'Pointed Gourd(Terai)': 'परवर(तराई)',
  'Snake Gourd': 'चिचिण्डो',
  'Smooth Gourd': 'घिरौला',
  'Sponge Gourd': 'झिगूनी',
  Pumpkin: 'फर्सी पाकेको',
  'Squash(Long)': 'फर्सी हरियो(लाम्चो)',
  'Squash(Round)': 'हरियो फर्सी(डल्लो)',
  Okara: 'भिण्डी',
  Christophine: 'स्कूस',
  'Brd Leaf Mustard': 'रायो साग',
  'Spinach Leaf': 'पालूगो साग',
  'Cress Leaf': 'चमसूरको साग',
  'Mustard Leaf': 'तोरीको साग',
  'Fenugreek Leaf': 'मेथीको साग',
  'Onion Green': 'प्याज हरियो',
  'Mushroom(Kanya)': 'च्याउ(कन्य)',
  'Mushroom(Button)': 'च्याउ(डल्ले)',
  Asparagus: 'कुरीलो',
  Neuro: 'न्यूरो',
  Brocauli: 'ब्रोकाउली',
  Sugarbeet: 'चुकुन्दर',
  'Red Cabbbage': 'रातो बन्दा',
  Lettuce: 'जिरीको साग',
  Knolkhol: 'ग्याठ कोबी',
  Celery: 'सेलरी',
  Parseley: 'पार्सले',
  'Fennel Leaf': 'सौफको साग',
  Mint: 'पुदीना',
  'Turnip A': 'गान्टे मूला',
  Tamarind: 'इमली',
  'Bamboo Shoot': 'तामा',
  Tofu: 'तोफु',
  Gundruk: 'गुन्दुक',
  'Apple(Fuji)': 'स्याउ(फूजी)',
  Banana: 'केरा',
  Lime: 'कागती',
  Pomegranate: 'अनार',
  'Mango(Maldah)': 'आँप(मालदह)',
  'Mango(Dushari)': 'आँप(दसहरी)',
  'Mango(Calcutte)': 'आँप(कलकत्ते)',
  'Grapes(Black)': 'अंगुर(कालो)',
  'Water Melon(Green)': 'तरबुजा(हरियो)',
  'Sweet Orange': 'मौसम',
  Mandarin: 'जुनार',
  Pineapple: 'भुई कटहर',
  'Cucumber(Local)': 'काक्रो(लोकल)',
  'Cucumber(Hybrid)': 'काक्रो(हाइब्रीड)',
  'Jack Fruit': 'रुख कटहर',
  'Papaya(Nepali)': 'मेवा(नेपाली)',
  'Papaya(Indian)': 'मेवा(भारतीय)',
  'Litchi(Local)': 'लीच्ची(लोकल)',
  'Litchi(Indian)': 'लीच्ची(भारतीय)',
  Kiwi: 'किवि',
  Avocado: 'आभोकाडो',
  Ginger: 'अदुवा',
  'Chilli Dry': 'खु्र्सानी सुकेको',
  'Chilli Green': 'खु्र्सानी हरियो',
  'Chilli Green(Bullet)': 'खुर्सानी हरियो(बुलेट)',
  'Chilli Green(Machhe)': 'खुर्सानी हरियो(माछे)',
  'Chilli Green(Akbare)': 'खुर्सानी हरियो(अकबरे)',
  Capsicum: 'भेडे खु्र्सानी',
  'Garlic Green': 'लसुन हरियो',
  'Coriander Green': 'हरियो धनिया',
  'Garlic Dry Chinese': 'लसुन सुकेको चाइनिज',
  'Garlic Dry Nepali': 'लसुन सुकेको नेपाली',
  'Clive Dry': 'छ्यापी सुकेको',
  'Clive Green': 'छ्यापी हरियो',
  'Fish Fresh(Rahu)': 'ताजा माछा(रहु)',
  'Fish Fresh(Bachuwa)': 'ताजा माछा(बचुवा)',
  'Fish Fresh(Chhadi)': 'ताजा माछा(छडी)',
  'Fish Fresh(Mungari)': 'ताजा माछा(मुंगरी)',
}

export default commodityMap
