name: Update data

on:
  schedule:
    - cron: 15,45 1,2,3 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm i axios@0.27.2 node-html-parser@5.3.3 axios-cookiejar-support@4.0.2 tough-cookie@4.0.0
      - name: Update data
        run: npm run update-data
      - name: Git check in
        run: |
          if [[ `git status --porcelain` ]]; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Update data for $(date +%Y-%m-%d)"
            git push
          else
            echo 'Nothing to check in'
          fi
