name: Update Data Daily

on:
  schedule:
    - cron: '25,30 12 * * *'
    # At NPT 07:55, 08:05, 08:15

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Fetch and update today's price data
        run: |
          yarn install
          yarn run update:daily:data

      - name: git check in
        env:
          GIT_OWNER_EMAIL: ${{ secrets.GIT_OWNER_EMAIL }}
          GH_PERSONAL_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
        run: |
          git config user.email "$GIT_OWNER_EMAIL"
          git config user.name "himalay"

          if [[ `git status --porcelain` ]]; then
            git add .
            git commit -a -m "Update daily price"
            git remote rm origin
            git remote add origin https://himalay:$GH_PERSONAL_TOKEN@github.com/himalay/kalimati
            git push origin HEAD:development
          else
            echo 'Nothing to check in'
          fi
